### ISSUE TITLE
WARN: index.ts compiled, but not written. Check your javascripts.joinTo config

### ISSUE THREAD

**Issue by hamadyne** [colinbate/ng2-brunch#5]
I'm getting the above warning message whenever I try to build the skeleton with `npm start`. Looking around, it appears that it could be a regex problem, [as detailed in this issue thread (starting with the comment by rodgomes)](https://github.com/phoenixframework/phoenix/issues/1495)

Below is the full log:

```
22 Apr 12:58:43 - info: application started on http://localhost:3333/
22 Apr 12:58:45 - info: compiling
22 Apr 12:58:47 - warn: C:\Users\tyler.WORKGROUP\Documents\GitHub\zenith-folio\app\directives\router-active.ts compiled, but not written. Check your javascripts.joinTo config
22 Apr 12:58:47 - warn: C:\Users\tyler.WORKGROUP\Documents\GitHub\zenith-folio\app\about\index.ts compiled, but not written. Check your javascripts.joinTo config
22 Apr 12:58:47 - warn: C:\Users\tyler.WORKGROUP\Documents\GitHub\zenith-folio\app\home\index.ts compiled, but not written. Check your javascripts.joinTo config
22 Apr 12:58:47 - warn: C:\Users\tyler.WORKGROUP\Documents\GitHub\zenith-folio\app\app.ts compiled, but not written. Check your javascripts.joinTo config
22 Apr 12:58:47 - warn: C:\Users\tyler.WORKGROUP\Documents\GitHub\zenith-folio\app\vendor.ts compiled, but not written. Check your javascripts.joinTo config
22 Apr 12:58:48 - info: compiled 415 files into 2 files, copied index.html in 6.2 sec
```

**Comment by colinbate** [comment]
I'll take a look. I know that certain versions of Brunch were a little bit broken, particularly on Windows. Can you confirm which version of Brunch you are using so I can test with the same?

**Comment by hamadyne** [comment]
I am using version 2.7.1 on Windows 7 Professional (Service Pack 1).

**Comment by colinbate** [comment]
OK, so the issue seems to be with Brunch. I'm going to update the skeleton with a specific version of brunch which I know works. I've also updated a number of other dependencies, including Angular 2 itself to bring it up to current.

When I get a chance I'll work with the brunch team to debug the issue further.

**Comment by hamadyne** [comment]
Okay, I'll do a re-install one you're all done.

**Comment by colinbate** [comment]
Pushed.
